project_name: frp-port-manager

before:
  hooks:
    - go mod tidy

env:
  - GO111MODULE=on

builds:
  - env:
      - CGO_ENABLED=0
    id: rush-linux
    ldflags:
      - -s -w
    main: main.go
    binary: frp-port-manager
    goos:
      - linux
      - windows
    goarch:
      - amd64

archives:
  - name_template: "{{.Os}}-{{.Arch}}{{if .Arm}}v{{.Arm}}{{end}}-{{ .ProjectName }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip